import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowUpRight, CalendarDays, Check, Clock3, MapPin, Users } from "lucide-react";
import { events } from "../../../lib/data";
import { SiteHeader } from "../../../components/site-header";

export function generateStaticParams() { return events.map((event) => ({ slug: event.slug })); }

export default function EventDetail({ params }: { params: { slug: string } }) {
  const event = events.find((item) => item.slug === params.slug);
  if (!event) notFound();
  return <main><div className={`relative overflow-hidden border-b border-line bg-gradient-to-br ${event.gradient} pt-36`}><SiteHeader /><div className="absolute inset-0 -z-10 bg-ink" /><div className="relative mx-auto max-w-5xl px-5 pb-24 lg:px-8"><Link href="/events" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={15} /> Back to events</Link><span className="mt-12 inline-block rounded-full border border-lime/30 bg-lime/10 px-3 py-1 text-xs font-semibold text-lime">{event.category}</span><h1 className="mt-5 max-w-3xl text-5xl font-semibold tracking-tight text-white md:text-7xl">{event.title}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">{event.description}</p><div className="mt-10 grid max-w-2xl gap-5 border-t border-white/10 pt-7 text-sm text-slate-300 sm:grid-cols-3"><div className="flex gap-3"><CalendarDays className="text-lime" size={18} /><span>{event.date}</span></div><div className="flex gap-3"><Clock3 className="text-lime" size={18} /><span>{event.time}</span></div><div className="flex gap-3"><MapPin className="text-lime" size={18} /><span>{event.location}</span></div></div></div></div><section className="mx-auto grid max-w-5xl gap-12 px-5 py-16 lg:grid-cols-[1fr_320px] lg:px-8"><div><h2 className="text-2xl font-semibold text-white">A room for people who care about the details.</h2><p className="mt-5 leading-8 text-slate-400">Bring the thing you are working on, the question you keep coming back to, or just an open mind. We keep this event small so every conversation can go somewhere.</p><h3 className="mt-10 font-semibold text-white">What to expect</h3><ul className="mt-4 space-y-3 text-sm text-slate-400"><li className="flex gap-3"><Check size={16} className="text-lime" />A thoughtful, no-pitch environment</li><li className="flex gap-3"><Check size={16} className="text-lime" />Lightning demos from club members</li><li className="flex gap-3"><Check size={16} className="text-lime" />Good snacks and better conversations</li></ul></div><aside className="h-fit rounded-2xl border border-line bg-panel p-6"><div className="flex items-center gap-3"><Users className="text-lime" size={18} /><span className="text-sm text-slate-300"><strong className="text-white">{event.attendees}</strong> / {event.capacity} attending</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-lime" style={{ width: `${(event.attendees / event.capacity) * 100}%` }} /></div><button className="mt-7 flex w-full items-center justify-center gap-2 rounded-xl bg-lime py-3.5 text-sm font-bold text-ink hover:bg-white">Reserve my spot <ArrowUpRight size={16} /></button><p className="mt-3 text-center text-[11px] text-slate-500">Members get priority access.</p></aside></section></main>;
}
